version: "3.8"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: form_app
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  symfony:
    build: ./symfony
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
    - ./symfony:/var/www/html
    command: ["sh", "/usr/local/bin/docker/entrypoint.sh", "php-fpm"]
    environment:
      APP_ENV: dev
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?serverVersion=${POSTGRES_VERSION}&charset=utf8"
    depends_on:
      db:
        condition: service_healthy

  nginx:
    image: nginx:stable-alpine
    container_name: symfony_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./symfony/.docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./symfony:/var/www/html
    depends_on:
      - symfony