version: "3.8"

services:
  db:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-form_app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-SomeR4nd0mPassword2313}
      POSTGRES_DB: ${POSTGRES_DB:-form_app}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB:-form_app}", "-U", "${POSTGRES_USER:-form_app}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - database_data:/var/lib/postgresql/data:rw

  symfony:
    build: ./symfony
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
    - ./symfony:/var/www/html
    command: ["sh", "/usr/local/bin/docker/entrypoint.sh", "php-fpm"]
    environment:
      COMPOSER_CACHE_DIR: '/tmp/composer-cache'
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?serverVersion=${POSTGRES_VERSION}&charset=utf8"
    depends_on:
      db:
        condition: service_healthy

  nginx:
    image: nginx:stable-alpine
    container_name: symfony_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./symfony/.docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./symfony:/var/www/html
    depends_on:
      - symfony

volumes:
  database_data: