nelmio_api_doc:
    documentation:
        info:
            title: API Formularza Kontaktowego
            description: Dokumentacja dla formularza kontaktowego.
            version: 1.0.0

    areas:
        default:
            path_patterns:
                - ^/api(?!/doc$)
    
    models:
      names:
          - alias: SubmitContactRequest
            type: App\UserInterface\Web\Request\SubmitContactRequest
            groups: [ 'Default' ]
          - alias: ContactSubmissionListItem
            type: App\Application\Query\ContactSubmissionListItem
            groups: [ 'Default' ]
          - alias: ContactSubmissionsResponse
            type: App\UserInterface\Web\Response\ContactSubmissionsResponse
            groups: [ 'Default' ]